export const GET_USER_REQUEST="GET_USER_REQUEST"
export const GET_USER_SUCESS="GET_USER_SUCESS"
export const GET_USER_FAILURE="GET_USER_FAILURE"

export const POST_USER_REQUEST="POST_USER_REQUEST"
export const POST_USER_SUCESS="POST_USER_SUCESS"
export const POST_USER_FAILURE="POST_USER_FAILURE"

export const DELETE_USER_REQUEST="DELETE_USER_REQUEST"
export const DELETE_USER_SUCESS="DELETE_USER_SUCESS"
export const DELETE_USER_FAILURE="DELETE_USER_FAILURE"

export const PATCH_USER_REQUEST="PATCH_USER_REQUEST"
export const PATCH_USER_SUCESS="PATCH_USER_SUCESS"
export const PATCH_USER_FAILURE="PATCH_USER_FAILURE"


